version: '3.1'
services:
  api:
    build: ./api
    container_name: api
    restart: always
    volumes:
      - ./api/:/var/www/html/api
      - ./index.php://var/www/html/index.php
    environment:
      - TZ=Asia/Bangkok
    expose:
      - "9000"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./api/:/var/www/html/api
      - ./index.php://var/www/html/index.php
    links:
      - api
    ports:
      - 8090:80
